/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p17.unidad4.vista;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import utp.misiontic2022.c2.p17.unidad4.controlador.Controlador;

/**
 *
 * @author 3mer
 */
public class BookShop_GUI extends javax.swing.JFrame {
    
    private Controlador controlador;
    private BooksTM booksTM;

    /**
     * Creates new form BookShop_GUI
     */
    public BookShop_GUI() {
        controlador = new Controlador();
        initComponents();
        cargarLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        pBooks = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spBooks = new javax.swing.JSplitPane();
        pFormBook = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idBook = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnSaveBook = new javax.swing.JButton();
        pTableBook = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        pbtnActBook = new javax.swing.JPanel();
        btnNewBook = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();
        pStock = new javax.swing.JPanel();
        pSales = new javax.swing.JPanel();
        mbBookShop = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        mWindow = new javax.swing.JMenu();
        miBooks = new javax.swing.JMenuItem();
        miStock = new javax.swing.JMenuItem();
        miSales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookShop");

        pBooks.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Libros");
        pBooks.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        spBooks.setDividerLocation(35);
        spBooks.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spBooks.setEnabled(false);

        jLabel2.setText("ID:");

        idBook.setEditable(false);
        idBook.setFocusable(false);

        jLabel3.setText("Title:");

        jLabel4.setText("ISBN:");

        jLabel5.setText("Year:");

        btnSaveBook.setText("Save");
        btnSaveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormBookLayout = new javax.swing.GroupLayout(pFormBook);
        pFormBook.setLayout(pFormBookLayout);
        pFormBookLayout.setHorizontalGroup(
            pFormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pFormBookLayout.setVerticalGroup(
            pFormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveBook))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        spBooks.setTopComponent(pFormBook);

        pTableBook.setMinimumSize(new java.awt.Dimension(300, 52));
        pTableBook.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 239));

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBooks);

        pTableBook.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pbtnActBook.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNewBook.setText("New");
        btnNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBookActionPerformed(evt);
            }
        });
        pbtnActBook.add(btnNewBook);

        btnDeleteBook.setText("Delete");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });
        pbtnActBook.add(btnDeleteBook);

        pTableBook.add(pbtnActBook, java.awt.BorderLayout.PAGE_END);

        spBooks.setRightComponent(pTableBook);

        pBooks.add(spBooks, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Books", pBooks);

        javax.swing.GroupLayout pStockLayout = new javax.swing.GroupLayout(pStock);
        pStock.setLayout(pStockLayout);
        pStockLayout.setHorizontalGroup(
            pStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pStockLayout.setVerticalGroup(
            pStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Stock", pStock);

        javax.swing.GroupLayout pSalesLayout = new javax.swing.GroupLayout(pSales);
        pSales.setLayout(pSalesLayout);
        pSalesLayout.setHorizontalGroup(
            pSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pSalesLayout.setVerticalGroup(
            pSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Sales", pSales);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.PAGE_START);

        mFile.setText("File");

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbBookShop.add(mFile);

        mWindow.setText("Window");

        miBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miBooks.setText("Books");
        miBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBooksActionPerformed(evt);
            }
        });
        mWindow.add(miBooks);

        miStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miStock.setText("Stock");
        miStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStockActionPerformed(evt);
            }
        });
        mWindow.add(miStock);

        miSales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LESS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSales.setText("Sales");
        miSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalesActionPerformed(evt);
            }
        });
        mWindow.add(miSales);

        mbBookShop.add(mWindow);

        setJMenuBar(mbBookShop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarLibros() {
        try {
            var books = controlador.findAllBooks();
            
            booksTM = new BooksTM(books);
            tblBooks.setModel(booksTM);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void miBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBooksActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_miBooksActionPerformed

    private void miStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStockActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_miStockActionPerformed

    private void miSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalesActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_miSalesActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicación?", 
                getTitle(),JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_miExitActionPerformed

    private void btnNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBookActionPerformed
        tblBooks.clearSelection();
        
        idBook.setText("");
        txtTitle.setText("");
        txtIsbn.setText("");
        txtYear.setText("");
        
        txtTitle.requestFocus();
    }//GEN-LAST:event_btnNewBookActionPerformed

    private void btnSaveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBookActionPerformed
        // Validar campos (title, isbn, year) - Que no esten vacios
        if (txtTitle.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El titulo es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtTitle.requestFocus();
        }
        
        if (txtIsbn.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El ISBN es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtIsbn.requestFocus();
        }
        
        if (txtYear.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El año es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtYear.requestFocus();
        }
        
        try {
            String id = idBook.getText();
            String title = txtTitle.getText().trim();
            String isbn = txtIsbn.getText().trim();
            Integer year = Integer.valueOf(txtYear.getText().trim());
            
            if (id.isBlank()) {
                var book = controlador.createBook(title, isbn, year);
                booksTM.addBook(book);
            } else {
                var row = tblBooks.getSelectedRow();
                var book = controlador.updateBook(isbn, title, year);
                
                booksTM.setBook(row, book);
            }
            
            JOptionPane.showMessageDialog(this, "Se ha guardado el libro!");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "A ocurrido un error al guardar el libro!", getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveBookActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        
        //controlador.deleteBook(ABORT);
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookShop_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnNewBook;
    private javax.swing.JButton btnSaveBook;
    private javax.swing.JTextField idBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mWindow;
    private javax.swing.JMenuBar mbBookShop;
    private javax.swing.JMenuItem miBooks;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miSales;
    private javax.swing.JMenuItem miStock;
    private javax.swing.JPanel pBooks;
    private javax.swing.JPanel pFormBook;
    private javax.swing.JPanel pSales;
    private javax.swing.JPanel pStock;
    private javax.swing.JPanel pTableBook;
    private javax.swing.JPanel pbtnActBook;
    private javax.swing.JSplitPane spBooks;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTabbedPane tpPrincipal;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
